### ISSUE TITLE
th.css not used when DEBUG=False

### ISSUE THREAD

**Issue by foxmask** [foxmask/django-th#252]
Even after a

```python
python manage.py collectstatic
```

The CSS is not used and return a 404 when we access to the app by 127.0.0.1:8000, but it"s found when using NGINX (for example)

**Comment by h-chauhan** [comment]
I am on it. :+1:

**Comment by alonisser** [comment]
This is expected behavior..  with DEBUG=False you local development server does not attempt to support static files and leaves it for the webserver (e.g nginx or apache) to handle. collectstatic only job is "collecting" the statics from different apps to the statics folder. from there it's the web server job.  While running with debug you don't need to collect statics..

**Comment by h-chauhan** [comment]
With DEBUG=False, you can run `python manage.py runserver --insecure` to make django server instead of production server serve the static files.

**Comment by foxmask** [comment]
@alonisser I thought about that.
So with debug to false, one cant just use the app on his/her desktop without setting up a http server.

**Comment by alonisser** [comment]
Using no secure is a bad option, Please notice the [docs](https://docs.djangoproject.com/en/1.11/ref/contrib/staticfiles/#cmdoption-runserver-insecure) about that

**Comment by alonisser** [comment]
@foxmask I'll send a PR explaining the options.

**Comment by foxmask** [comment]
@alonisser to explain what i'd like:

Recently someone installed the app on his desktop, all is ok and work fine. 
But the app runs in debug. (I did not set debug to false when she clone the repo). 
As she has no knowledge in sys admin ; it's complicated for an end user to make them understand of the aspect of those things. So If I tell her ; set DEBUG to False, the render will be "broken".
This is why I expected to be able to display the CSS with debug to false without setting up a HTTP server.
The solution I can see is to embed the css in the main html file. But it's not so nice :/
I'll read your suggestions with pleasure.

**Comment by alonisser** [comment]
@foxmask Maybe I'm missing something. Is the intended setup of this project to run on a personal laptop of a non technical person? If so then I would suggest packaging it better.. (maybe composed dockers + a run command to abstract it? Maybe something else), currently It's packaged as a professional software development project. 
If this is a specific edge case, which is not the intended use of the project, then by all means, let them run with DEBUG=True, or with "runserver --unsecure" (can be wrapped in a shell/batch script to hide this fact) while professional deployments are deployed as designed .
I've seen far too many professional django deployments running with DEBUG=True because people don't know how to solve this and I think explaining the correct solution is better

**Comment by foxmask** [comment]
it's packaged to be use as professional software project, yes.
In my previous comment, I explained a specific use case, so ok for DEBUG=True or runserver --insecure will do the trick.
Thank you for all the explanations

**Comment by foxmask** [comment]
thanks you to both of you
